server:
  port: 9000
spring:
  servlet:
    multipart:
      max-file-size: 10000MB
      max-request-size: 10000MB
  application:
    name: blog
  datasource:
    url: jdbc:mysql://${MYSQL}:3306/video?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver